
##################################################
###   Visit https://github.com/tinybirdco/ci   ###
###   for more details or custom CI/CD         ###
##################################################

name: Tinybird - CI Workflow

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'tinybird/**'
    branches:
      - main
    types: [opened, reopened, labeled, unlabeled, synchronize, closed]

concurrency: ${{ github.workflow }}-${{ github.event.pull_request.number }}

jobs:
    ci:
      uses: tinybirdco/ci/.github/workflows/ci.yml@v4.1.0
      with:
        data_project_dir: ./tinybird
        use_last_partition: false
      secrets:
        tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN }}
        tb_host: https://api.tinybird.co